platform :ios, '13.0'

# Local pods for Kim
def localPods
  pod 'ZXYModels', :path => './ThirdPartFrameworks/ZXYModels'
end

target 'ZXYRSSClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for ZXYRSSClient
  localPods
end